### PR TITLE
Fix sink, add sink tests, make TCP.Socket private

### LINKED ISSUE #760: `TCP.Sink` with `connection_side: :client` does not work
Element was created with
```elixir
 %TCP.Sink{
    connection_side: :client,
    server_port_no: input_port,
    server_address: @local_host
 }
```

Local unconnected socket is created here https://github.com/membraneframework/membrane_tcp_plugin/blob/master/lib/membrane_tcp/socket.ex#L34

but it failes here https://github.com/membraneframework/membrane_tcp_plugin/blob/master/lib/membrane_tcp/socket.ex#L54

If I understand correctlly implementation is assuming that already connected socket was already passed there. It looks like `server_port_no` and `server_address` options are never used

```
** (Membrane.ParentError) Error starting child {:tcp_sink, 0}, reason: {:function_clause, [{:prim_inet, :peername, [nil], []}, {Membrane.TCP.Socket, :create_socket_pair, 2, [file: ~c"lib/membrane_tcp/socket.ex", line: 54]}, {Membrane.TCP.Sink, :handle_init, 2, [file: ~c"lib/membrane_tcp/sink.ex", line: 63]}, {Membrane.Core.CallbackHandler, :exec_callback, 4, [file: ~c"lib/membrane/core/callback_handler.ex", line: 139]}, {Membrane.Core.CallbackHandler, :exec_and_handle_callback, 5, [file: ~c"lib/membrane/core/callback_handler.ex", line: 69]}, {Membrane.Core.Element, :init, 1, [file: ~c"lib/membrane/core/element.ex", line: 166]}, {:gen_server, :init_it, 2, [file: ~c"gen_server.erl", line: 980]}, {:gen_server, :init_it, 6, [file: ~c"gen_server.erl", line: 935]}]}
    (membrane_core 1.0.0) lib/membrane/core/parent/child_life_controller/startup_utils.ex:225: Membrane.Core.Parent.ChildLifeController.StartupUtils.start_child/6
    (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (membrane_core 1.0.0) lib/membrane/core/parent/child_life_controller.ex:253: Membrane.Core.Parent.ChildLifeController.setup_children/3
    (elixir 1.16.0) lib/enum.ex:1301: anonymous fn/3 in Enum.flat_map_reduce/3
    (elixir 1.16.0) lib/enum.ex:4842: Enumerable.List.reduce/3
    (elixir 1.16.0) lib/enum.ex:1300: Enum.flat_map_reduce/3
```

### PR DESCRIPTION
**Pull request by Noarkhh**
closes https://github.com/membraneframework/membrane_core/issues/760

### CODE REVIEW

**Comment by wkozyra95** [comment]
I can confirm it fixes the https://github.com/membraneframework/membrane_core/issues/760
Any ETA when it will land?

**Comment by Noarkhh** [comment]
I just put it in review, should be done soon

File: lib/membrane_tcp/common_socket_behaviour.ex [hunk 1]
```diff
@@ -10,7 +10,7 @@ defmodule Membrane.TCP.CommonSocketBehaviour do
           Base.callback_return()
   def handle_setup(
         ctx,
-        %{connection_side: :client, local_socket: local_socket, server_socket: server_socket} =
+        %{connection_side: :client, local_socket: local_socket, remote_socket: server_socket} =
```
Comment (mat-hek) [inline lib/membrane_tcp/common_socket_behaviour.ex:13]:
```suggestion
        %{connection_side: :client, local_socket: local_socket, remote_socket: remote_socket} =
```

File: test/membrane_tcp/sink/pipeline_test.exs [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+    Socket.close(socket)
+  end
+
+  defp receive_data(socket, received_data \\ "", terminator \\ ".") do
+    {:ok, payload} = Socket.recv(socket)
+
+    if String.ends_with?(payload, terminator) do
+      received_data <> payload
+    else
+      receive_data(socket, received_data <> payload)
```
Comment (varsill) [inline test/membrane_tcp/sink/pipeline_test.exs]: shouldn't you also pass the `terminator` here? :p

File: test/membrane_tcp/sink/pipeline_test.exs [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+                 sock_opts: [active: false]
+               }
+               |> Socket.connect(%Socket{
+                 connection_side: :server,
+                 ip_address: @localhost,
+                 port_no: @server_port_no
+               })
+
+      # time for a pipeline to enter playing playback
+      Process.sleep(200)
```
Comment (varsill) [inline test/membrane_tcp/sink/pipeline_test.exs]: cannot you use `assert_sink_playing`?

File: test/membrane_tcp/source/pipeline_test.exs [hunk 4]
```diff
@@ -80,5 +114,23 @@ defmodule Membrane.TCP.SourcePipelineTest do
       Process.sleep(100)
       run_pipeline(pipeline, server_socket)
     end
+
+    test "server-side pipeline created with an already connected socket" do
+      {client_socket, server_socket} = create_connected_socket_pair()
+
+      assert pipeline =
```
Comment (varsill) [inline test/membrane_tcp/source/pipeline_test.exs]: I guess it will always match, so I don't think you need that `assert` here

File: test/membrane_tcp/sink/pipeline_test.exs (hunk 2 above)
Comment (Noarkhh) [reply test/membrane_tcp/sink/pipeline_test.exs]: no, because the payload already ends with terminator

File: lib/membrane_tcp/sink.ex [hunk 5]
```diff
@@ -8,27 +8,15 @@ defmodule Membrane.TCP.Sink do
...
-              ],
-              server_port_no: [
-                spec: :inet.port_number() | nil,
-                default: nil,
-                description: """
-                A TCP port number of the server the packets will be sent to.
-                (nil in case of `connection_side: :server`)
+                Determines whether this element will operate like a server or a client when
+                establishing TCP connection. In case of client-side connection server address
+                and port number are required, unless `local_socket` is provided.
```
Comment (mat-hek) [inline lib/membrane_tcp/sink.ex:19]: As far as I understand, some information is duplicated between this option and `local_socket`, so I'd suggest that `local_socket` could just accept `:gen_tcp.socket`

**Review by mat-hek — CHANGES_REQUESTED** [review]

File: test/membrane_tcp/sink/pipeline_test.exs (hunk 2 above)
Comment (varsill) [reply test/membrane_tcp/sink/pipeline_test.exs]: but you are loosing an information about the desired `terminator`

File: test/membrane_tcp/sink/pipeline_test.exs (hunk 3 above)
Comment (Noarkhh) [reply test/membrane_tcp/sink/pipeline_test.exs]: not really since I'm not using a testing source

File: lib/membrane_tcp/common_socket_behaviour.ex (hunk 1 above)
Comment (Noarkhh) [reply lib/membrane_tcp/common_socket_behaviour.ex:13]: In this case the remote_socket is a server-side socket

File: lib/membrane_tcp/socket.ex [hunk 6]
```diff
@@ -19,34 +17,49 @@ defmodule Membrane.TCP.Socket do
...
+            connection_side: sockets_config.connection_side
           }
 
-        %__MODULE__{connection_side: ^connection_side, state: :connected} ->
-          local_socket
+        socket_handle ->
+          {:ok, {socket_address, socket_port}} = :inet.sockname(socket_handle)
+
+          if sockets_config.local_address not in [socket_address, :any] do
+            raise "Local address passed in options not mathing the one of the passed socket."
```
Comment (varsill) [inline lib/membrane_tcp/socket.ex]:
```suggestion
            raise "Local address passed in options not matching the one of the passed socket."
```

File: lib/membrane_tcp/socket.ex [hunk 7]
```diff
@@ -19,34 +17,49 @@ defmodule Membrane.TCP.Socket do
...
+          end
+
+          if sockets_config.local_port_no not in [socket_port, 0] do
+            raise "Local port passed in options not mathing the one of the passed socket."
```
Comment (varsill) [inline lib/membrane_tcp/socket.ex]:
```suggestion
            raise "Local port passed in options not matching the one of the passed socket."
```

File: lib/membrane_tcp/socket.ex [hunk 8]
```diff
@@ -19,34 +17,49 @@ defmodule Membrane.TCP.Socket do
...
+          end
 
-        _not_matching_connection_side_socket ->
-          raise "Connection side of provided socket not matching options"
+          if not match?({:ok, _peername}, :inet.peername(socket_handle)) do
+            raise "Local socket not connected."
+          end
```
Comment (varsill) [inline lib/membrane_tcp/socket.ex]: [NIT] You could aggregate these statements into a single `cond do ... end` clause

**Review by varsill — APPROVED** [review]
